### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by idahogurl** [sckott/usdaplantsapi#10]
I attempted accessing your API and your service appears to be down.

**Comment by sckott** [comment]
try https://plantsdb.xyz/heartbeat or https://plantsdb.xyz/search 

if you do https://plantsdb.xyz sometimes it will error on you, still trying to figure that out.

**Comment by sckott** [comment]
it is actually down right now for another, will be back up soon

**Comment by sckott** [comment]
back up now
