### ISSUE TITLE
Retiring this API next week

### ISSUE THREAD

**Issue by sckott** [sckott/usdaplantsapi#15]
Just an FYI for anyone watching this repo

USDA has an API now, maybe its not great, but running this costs money and there really isn't that much use anyway

**Comment by libertyjayne** [comment]
@sckott - I'm having trouble accessing the USDA API. Do you have any information about it?

**Comment by sckott** [comment]
see https://github.com/USDA/USDA-APIs/issues/7#issuecomment-557136892

**Comment by libertyjayne** [comment]
Thanks so much!
