### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by sckott** [sckott/usdaplantsapi#3]
@dlebauer  pinging you here instead of the usda repo

the readme has instructions https://github.com/sckott/usdaplantsapi#base-url

let me know what you think

I only have the original data you provided from this comment https://github.com/USDA/USDA-APIs/issues/7#issuecomment-187931791

**Comment by dlebauer** [comment]
@sckott this looks good, but I'd suggest using the file [usda_plants_20160223.csv](https://uofi.box.com/s/cx1vuvn1qzl3kctf5hb31otp9r65xuva) from a subsequent comment (https://github.com/USDA/USDA-APIs/issues/7#issuecomment-188002148). This is a copy of the database from Feb 23 2016; the other ones are five or more years old and the original content has not been preserved.

**Comment by sckott** [comment]
okay, will do

**Comment by dlebauer** [comment]
One other thought: the current documentation suggests that the search endpoint is currently used to define which fields are returned (as in `select genus, species, accepted symbol from plants`). 

Another very useful feature would be to be able to subset analogous to a `where` clause like `... where genus = 'Acer';` etc.

In the development version of the BETYdb API this would be something like [`species?genus=Acer`](http://pecandev.igb.illinois.edu/beta/api/v0/species?genus=Acer&key=9999999999999999999999999999999999999999&limit=20)

**Comment by sckott** [comment]
Right, the last bullet point in the `params` header describes that https://github.com/sckott/usdaplantsapi#params - ability to search, that is, where statements

**Comment by dlebauer** [comment]
Got it. Thanks!

**Comment by sckott** [comment]
API now using the newer dataset
